databases:
  - name: moochat
    databaseName: moochat
    user: moochat

services:
  - type: web
    name: moochat
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn moochat.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: moochat
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4